keyword_to_token = {
    "bitcoin": "BTC",
    "btc": "BTC",
    "ethereum": "ETH",
    "eth": "ETH",
    "bnb": "BNB",
    "binance": "BNB",
    "binance coin": "BNB",
    "solana": "SOL",
    "sol": "SOL",
    "matic": "MATIC",
    "polygon": "MATIC",
    "blockchain": "BLOCKCHAIN",
    "trading": "TRADING",
    "defi": "DEFI",
    "dapps": "DAPPS",
    "Binance": "BNB",
    "Binance Coin": "BNB",
    "Solana": "SOL",
    "Matic": "MATIC",
}
